repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.2.0
    hooks:
      - id: check-yaml
        name: Check SAM template yml file
        files: template.yaml
        args: ['--unsafe']
      - id: check-yaml
        name: Check normal yml files
        exclude: template.yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=crlf'
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - '--maxkb=5000'
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ['--branch=prod']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
  - repo: 'https://github.com/PyCQA/autoflake'
    rev: v2.1.1
    hooks:
      - id: autoflake
  - repo: 'https://github.com/psf/black'
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args: []
        files: .
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: 'https://github.com/dhruvmanila/remove-print-statements'
    rev: v0.5.1
    hooks:
      - id: remove-print-statements
        args:
          - '--verbose'
  - repo: 'https://github.com/PyCQA/bandit'
    rev: 1.7.5
    hooks:
      - id: bandit

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--ignore=D100,D203,D212,D213,D400,D401,D405,D406,D407,D413,D415']