[tool.isort]
profile = "black"
line_length = 150
multi_line_output = 3
skip_gitignore = true
include_trailing_comma = true


[tool.black]
line-length = 150
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''